[build]
  base = "/"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF mathsWeb/"
  command = "npm run build"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "19"  # Match your React version

